name: Build GNOME Sudoku AppImage

on:
  push:
    branches: [ "main" ]
    paths:
      - './**'
      - '.github/workflows/build-sudoku.yml'
    tags: [ "sudoku-v*" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y 
            build-essential meson ninja-build pkg-config wget git 
            vala libgtk-4-dev libadwaita-1-dev libgee-0.8-dev 
            libjson-glib-dev libqqwing-dev yelp-tools

      - name: Build AppImage
        run: bash build/build-gnome-sudoku-appimage.sh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: GNOME-Sudoku-AppImage
          path: "./*.AppImage"

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/sudoku-v')

    steps:
      - name: Download AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: GNOME-Sudoku-AppImage

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.AppImage"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
