name: Build AppImage
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            build-essential \
            python3-pip \
            python3-setuptools \
            python3-venv \
            ninja-build \
            pkg-config \
            wget \
            git \
            valac \
            libgee-0.8-dev \
            libjson-glib-dev \
            libqqwing-dev \
            yelp-tools \
            itstool \
            gettext \
            libxml2-utils \
            libxml2-dev \
            desktop-file-utils \
            libgirepository1.0-dev \
            libglib2.0-dev \
            libpango1.0-dev \
            libcairo2-dev \
            libgdk-pixbuf-2.0-dev \
            libepoxy-dev \
            libgraphene-1.0-dev \
            libwayland-dev \
            libx11-dev \
            libxkbcommon-dev \
            libvulkan-dev \
            libadwaita-1-dev \
            libgtk-4-dev \
            libffi-dev \
            zlib1g-dev \
            libmount-dev \
            libselinux1-dev \
            libpcre2-dev \
            python3-dev \
            libdbus-1-dev \
            python3-gi \
            mount
          pip3 install --break-system-packages --upgrade meson ninja
      - name: Build
        run: bash build/build-gnome-sudoku-appimage.sh
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sudoku-AppImage
          path: "*.AppImage"

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: Sudoku-AppImage
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          files: "*.AppImage"
          generate_release_notes: true
          draft: true
          prerelease: ${{ github.ref_name == 'main' }}
          make_latest: ${{ github.ref_name != 'main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
